### PR TITLE
[SofaBoundaryCondition] FIX AffineMovementConstraint orientation issue

### LINKED ISSUE #795: AffineMovementConstraint: orientation issue
Christiane, a SOFA user noticed an issue regarding the orientation of the frames (Rigid3dTypes) with the AffineMovementConstraint. 

The final rotation is obtained by adding the initial orientation quaternion and the rotation quaternion. Normally, combining rotations is done by multiplying quaternions, not by adding them; in fact, a quaternion addition will not yield a unity quaternion, hence the result is not a rotation. There’s probably a check on the Rigid3Types which prevents keeping this non-unity quaternion as the orientation, and the end result is that I see my properly oriented beam segments go back to not being oriented until the end of the displacement, when they are reset to their original orientation.

See [original forum post](https://www.sofa-framework.org/community/forum/topic/rotation-problem-with-affinemovementconstraint-and-beamfemforcefield/)

______________________________________________________

Suggested labels:

### PR DESCRIPTION
**Pull request by olivier-goury**
Fix #795 hopefully .
Problem comes from the interpolation between starting and final position: was working well for vec3d but not well for Rigids by messing up the quaternion.
New implementation not optimum as some code bits are copy-pasted.
Please comment!
Olivier

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build][with-scene-tests]

**Comment by damienmarchal** [comment]
Ok so I defintely breaks something in this PR. Let's look at it. 
 
NB: oups.. I commited the FixedPlanedConstraint which shouldn't :) it is just there to allow gcc 8.1 to compile Sofa.

File: modules/SofaBoundaryCondition/AffineMovementConstraint.cpp [hunk 1]
```diff
@@ -37,29 +38,26 @@ namespace component
 namespace projectiveconstraintset
 {
 
-//declaration of the class, for the factory
-SOFA_DECL_CLASS(AffineMovementConstraint)
-
-
-int AffineMovementConstraintClass = core::RegisterObject("bilinear constraint")
-#ifndef SOFA_FLOAT
+auto tmp = core::RegisterObject("bilinear constraint")
```
Comment (damienmarchal) [inline modules/SofaBoundaryCondition/AffineMovementConstraint.cpp]: of course nothing is working :)

**Comment by damienmarchal** [comment]
Current the component says it:
/** 
    Impose a motion to all the boundary points of a mesh. The motion of the 4 corners are given in the data m_cornerMovements and the movements of the edge points are computed by linear interpolation. 
*/
Which looks wrong and probably the result of copy-pasting. 
But what should it be instead ? 

Then I bumped into these two:
```cpp
, m_beginConstraintTime( initData(&m_beginConstraintTime,"beginConstraintTime","Begin time of the bilinear constraint") )
    , m_endConstraintTime( initData(&m_endConstraintTime,"endConstraintTime","End time of the bilinear constraint") )
  ```
I dream of a day when this kind of code will be removed (or moved into single "unique" component that controls "activation/deactivation" of a component according to specific rules (time, key, message whatever)).
