### PR TITLE
[Sofa.Core] Move eq,peq utilities functions to a standalone file

### LINKED ISSUE #2122: Remove helper::{eq,peq} from IdentityMapping
IdentityMapping.h possesses some helper functions (eq & peq on float <-> double, and Coord <->OtherCoord):
 - so namespace is wrong
 - it should not be here
 - only used in mappings apparently

Possible solution: add some functions for Rigid (in defaulttype::Rigid), use only CPos for VecTypes and use if constepxr in the mappings using those functions

#2090

### PR DESCRIPTION
**Pull request by fredroy**
eq/peq() functions defined in IdentityMapping should be moved elsewhere; no need to know IdentityMapping to use them.

These functions are now located in a file core/MappingHelper.h alongside Mapping.h, as these functions would likely be used only by mappings.

Some points to discuss:
 - header filename ?
 - eq/peq functions name themselves are not very informative... should it be assign() and add() for example ?

Fix #2122 

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

File: SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/IdentityMapping.h [hunk 1]
```diff
@@ -153,131 +150,97 @@ extern template class SOFA_SOFABASEMECHANICS_API IdentityMapping< defaulttype::R
 
 namespace sofa::helper
 {
-    // should certainly be somewhere else
-    // but at least it is accessible to other components
 
+#define SOFA_ATTRIBUTE_DISABLED__HELPER_EQ() \
+    SOFA_ATTRIBUTE_DISABLED( \
+        "v21.06 (PR#21XX)", "v21.06", "You need to include <sofa/core/MappingHelper.h> and use sofa::core::eq(...) instead)")
```
Comment (guparan) [inline SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/IdentityMapping.h]:
```suggestion
        "v21.06 (PR#2137)", "v21.06 (PR#2137)", "You need to include <sofa/core/MappingHelper.h> and use sofa::core::eq(...) instead.")
```

File: SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/IdentityMapping.h [hunk 2]
```diff
@@ -153,131 +150,97 @@ extern template class SOFA_SOFABASEMECHANICS_API IdentityMapping< defaulttype::R
...
 
-    template<class T1, class T2>
-    static inline void eq(T1& dest, const T2& src)
-    {
-        dest = src;
-    }
+#define SOFA_ATTRIBUTE_DISABLED__HELPER_PEQ() \
+    SOFA_ATTRIBUTE_DISABLED( \
+        "v21.06 (PR#21XX)", "v21.06", "You need to include <sofa/core/MappingHelper.h> and use sofa::core::peq(...) instead)")
```
Comment (guparan) [inline SofaKernel/modules/SofaBaseMechanics/src/SofaBaseMechanics/IdentityMapping.h]:
```suggestion
        "v21.06 (PR#2137)", "v21.06 (PR#2137)", "You need to include <sofa/core/MappingHelper.h> and use sofa::core::peq(...) instead.")
```

**Review by guparan — CHANGES_REQUESTED** [review]

**Review by guparan — APPROVED** [review]

**Comment by alxbilger** [comment]
I am for a discussion on the filename. I assume it could be used in other places than mappings.
