### PR TITLE
[HyperElastic] Enable unit tests for off-diagonal elements of the elasticity tensor

### LINKED ISSUE #5739: Failing tests for off-diagonal elasticity tensor components for hyperelastic models
### Some context

There are a number of classes implementing material models in `Sofa/Component/SolidMechanics/FEM/HyperElastic/src/sofa/component/solidmechanics/fem/hyperelastic/material`. The `Sofa/Component/SolidMechanics/FEM/HyperElastic/tests/Material_test.cpp` file tests 3 functions: `deriveSPKTensor`, `applyElasticityTensor` and `ElasticityTensor`, implemented by these classes. 
Here we are looking at models that already pass these tests.

### The issue
Currently, the test for the `ElasticityTensor` is incomplete as it checks only the diagonal components of the tensor. 
https://github.com/sofa-framework/sofa/blob/98ae9076648db7cb3e3009279e0937c8b5e88a5b/Sofa/Component/SolidMechanics/FEM/HyperElastic/tests/Material_test.cpp#L189-L190
If you activate the off-diagonal test, all components fail. But... it's just that the off-diagonal entries are multiplied by 2. e.g. from the `VerondaWestman`
Image

This is the case for all models and I would assume that this multiplication is put in place on purpose. Maybe it's convenient to store the tensor like this (due to symmetry)?

Does anyone know whether this is by design or a mistake?

### PR DESCRIPTION
**Pull request by th-skam**
The unit tests for hyperelastic material models skip verification of the off-diagonal elasticity tensor components.

These components are intentionally stored with a 2x factor. Only the `StandardTetrahedralFEMForceField` uses the tensor explicitly and does account for the 2x factor (see #5739).

We should enable the unit tests for these terms and have a reference for new model implementations.
Close #5739

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

File: Sofa/Component/SolidMechanics/FEM/HyperElastic/tests/Material_test.cpp [hunk 1]
```diff
@@ -199,12 +198,12 @@ void testElasticityTensorFromSecondPiolaKirchhoff(
...
         //ElasticityTensor = 2 * dPK2/dC
-        const MatrixSym elasticityTensorApprox = 2 * centralDifference;
+        MatrixSym elasticityTensorApprox = 2 * centralDifference;
 
         //compare the approximation of the elasticity tensor
-        // for (sofa::Size j = 0; j < Matrix6::size(); ++j)
-        for (sofa::Size j : {0, 2, 5}) //only the diagonal terms
+        for (sofa::Size j = 0; j < Matrix6::size(); ++j)
         {
+            if (j == 1 || j == 3 || j == 4) elasticityTensorApprox[j] *= 2.;
```
Comment (alxbilger) [inline Sofa/Component/SolidMechanics/FEM/HyperElastic/tests/Material_test.cpp:207]: Could you just add a comment why you multiply by 2?

**Review by bakpaul — APPROVED** [review]

**Review by alxbilger — APPROVED** [review]
