### PR TITLE
[SofaGuiQt] FIX screenshot mechanism

### LINKED ISSUE #1791: Screenshot button malfunctionning
The screenshot button of the GUI returns me a black image.
We should use the same export than with the "S" shortcut

### PR DESCRIPTION
**Pull request by guparan**
Fixes #1791 

Screenshot mechanism was broken and inconsistent between viewers.

With this PR, using the screenshot button or pressing "S" will do the same thing, regardless of the viewer.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

File: modules/SofaGuiQt/src/sofa/gui/qt/RealGUI.cpp [hunk 1]
```diff
@@ -1466,10 +1471,10 @@ BaseViewer* RealGUI::getViewer()
 
 //------------------------------------
 
-sofa::gui::qt::viewer::SofaViewer* RealGUI::getQtViewer()
+sofa::gui::qt::viewer::SofaViewer* RealGUI::getSofaViewer()
 {
-    sofa::gui::qt::viewer::SofaViewer* qtViewer = dynamic_cast<sofa::gui::qt::viewer::SofaViewer*>(mViewer);
-    return qtViewer ? qtViewer : nullptr;
+    sofa::gui::qt::viewer::SofaViewer* sofaViewer = dynamic_cast<sofa::gui::qt::viewer::SofaViewer*>(mViewer);
+    return sofaViewer ? sofaViewer : nullptr;
```
Comment (alxbilger) [inline modules/SofaGuiQt/src/sofa/gui/qt/RealGUI.cpp]:
```suggestion
    return dynamic_cast<sofa::gui::qt::viewer::SofaViewer*>(mViewer);
```

**Comment by guparan** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
@hugtalbot did you try on your side ? (as you are the creator of the issue #1791 😗 )

**Review by hugtalbot — APPROVED** [review]
