### PR TITLE
[SofaBaseTopology] Fix SparseGridTopology initialization with an input mesh

### LINKED ISSUE #308: SparseGrid : translation imposed
A bug has been reported by a user (Cristóbal) in the forum : https://www.sofa-framework.org/community/forum/topic/vertices-from-obj-are-moved/

The SparseGrid seems to shift the mesh. This might be due to "max" Data is related to the BBox.
Whatever, strange behaviour.

### PR DESCRIPTION
**Pull request by hugtalbot**
Fixes #308 with initialization of SparseGridTopology with a mesh

Before, a 1% scaling was automatically applied on the grid bounding an input mesh. Removing the scaling was leading a crash since vertices could be exactly on the boundary surface (surface of the BBox of the mesh).
Now a safety check is done and a final check is done to alert if a vertex is not found.

Minor cleans of the msg API are also added.

@epernod @fredroy your feedback using your own scenes involving the SparseGrid would be useful.

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

File: SofaKernel/modules/SofaBaseTopology/SparseGridTopology.cpp [hunk 1]
```diff
@@ -1419,8 +1426,8 @@ void SparseGridTopology::buildVirtualFinerLevels()
     _virtualFinerLevels[0]->_fillWeighted.setValue( _fillWeighted.getValue() );
     _virtualFinerLevels[0]->init();
 
-    sout<<"SparseGridTopology "<<getName()<<" buildVirtualFinerLevels : ";
-    sout<<"("<<newnx<<"x"<<newny<<"x"<<newnz<<") -> "<< _virtualFinerLevels[0]->getNbHexahedra() <<" elements , ";
+    msg_info()<<"SparseGridTopology "<<getName()<<" buildVirtualFinerLevels : " << msgendl;
```
Comment (damienmarchal) [inline SofaKernel/modules/SofaBaseTopology/SparseGridTopology.cpp]: There is no needs for msgendl at he end of message it is only to separate lines within a message.

File: SofaKernel/modules/SofaBaseTopology/SparseGridTopology.cpp [hunk 2]
```diff
@@ -1419,8 +1426,8 @@ void SparseGridTopology::buildVirtualFinerLevels()
...
+    msg_info()<<"("<<newnx<<"x"<<newny<<"x"<<newnz<<") -> "<< _virtualFinerLevels[0]->getNbHexahedra() <<" elements , " << msgendl;
```
Comment (damienmarchal) [inline SofaKernel/modules/SofaBaseTopology/SparseGridTopology.cpp]: It is better (more efficient, more clear) to have a single message with multiple lines in it instead of two message.

Comment (damienmarchal) [reply SofaKernel/modules/SofaBaseTopology/SparseGridTopology.cpp]: Here is an example of one message without line breaks. 
```cpp
 msg_info() <<"("<<newnx<<"x"<<newny<<"x"<<newnz<<") ->   "<<_virtualFinerLevels[0]->getNbHexahedra() <<" elements , " 

<<"("<<_virtualFinerLevels[i]->getNx()<<"x"<<_virtualFinerLevels[i]->getNy()

<<"x"<<_virtualFinerLevels[i]->getNz()<<") -> "<< _virtualFinerLevels[i]->getNbHexahedra() <<" elements , "
```

If you want linebreaks into a message...add msgendl where you want the break.

File: SofaKernel/modules/SofaBaseTopology/SparseGridTopology.cpp [hunk 3]
```diff
@@ -840,38 +832,45 @@ void SparseGridTopology::voxelizeTriangleMesh(helper::io::Mesh* mesh,
     const helper::vector< Vector3 >& vertices = mesh->getVertices();
     const size_t vertexSize = vertices.size();
     helper::vector< int > verticesHexa(vertexSize);
-    helper::vector< bool > facetDone;
     const Vector3 delta = (regularGrid->getDx() + regularGrid->getDy() + regularGrid->getDz()) / 2;
```
Comment (epernod) [inline SofaKernel/modules/SofaBaseTopology/SparseGridTopology.cpp:835]: Not sure about this Delta value, If I understand well. If one of the direction is very big and the other are small. You could miss some points in the "big" resolution direction in your test below.

File: SofaKernel/modules/SofaBaseTopology/SparseGridTopology.cpp (hunk 2 above)
Comment (hugtalbot) [reply SofaKernel/modules/SofaBaseTopology/SparseGridTopology.cpp]: Does my latest commit do what you expected @damienmarchal ?

**Review by epernod — APPROVED** [review]

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
@hugtalbot, the change seems to break 2 scene tests. Will you have time to check if they are false negative due to the BB change?

https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/PR-670/CI_CONFIG=centos_clang-3.4,CI_PLUGINS=options,CI_TYPE=release/5/warnings3Result/

File: SofaKernel/modules/SofaBaseTopology/SparseGridTopology.cpp (hunk 3 above)
Comment (hugtalbot) [reply SofaKernel/modules/SofaBaseTopology/SparseGridTopology.cpp:835]: this could explain the crashing scene, but I don't get why actually. Why could I miss some points in the "big" resolution direction?

**Comment by epernod** [comment]
@hugtalbot this is not me above :)

File: SofaKernel/modules/SofaBaseTopology/SparseGridTopology.cpp (hunk 3 above)
Comment (epernod) [reply SofaKernel/modules/SofaBaseTopology/SparseGridTopology.cpp:835]: not sure to remember exactly what mean Dx, Dy and Dz as they are 3D. 
But in a general way in 1 dimension, if for example: Dx = 1000 and Dy = Dz = 10.
delta = 1020/2 = 510.
So when looking at next point in Dx direction, if the scale is ~1000, your delta of 510 is too small.
