### PR TITLE
[SofaBoundaryCondition_test] Add TopologicalChanges unit test for FixedConstraint

### LINKED ISSUE #1589: Crash when combining FixConstraint and topologyModifier
See scene in PR #1573

### PR DESCRIPTION
**Pull request by epernod**
unit Test for FixConstraint class to test topologicalChanges

Fix #1589

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp [hunk 1]
```diff
@@ -156,6 +158,91 @@ struct FixedConstraint_test : public BaseTest
...
+        /// Add Mass
+        createUniformMass<DataTypes>(node, *dofs.get());
+
+        /// Add force
+        typename ForceField::SPtr forceField = addNew<ForceField>(node);
+        
+        // create a force vector
+        Deriv force;
+        for (unsigned i = 0; i < force.size(); i++)
+            force[i] = 10;
```
Comment (guparan) [inline modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp]: Is it possible to write `Deriv force = { 10 };` ?

Comment (epernod) [reply modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp]: Error	C2440	'initializing': cannot convert from 'initializer list' to 'sofa::defaulttype::RigidDeriv<3,real>'

**Comment by epernod** [comment]
issue #1589 could be closed after merging this PR. It has already been solved in a previous PR but this one add a test related to the reported bug.

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp [hunk 2]
```diff
@@ -156,6 +158,91 @@ struct FixedConstraint_test : public BaseTest
...
+
+        /// Fill position and force
+        typename MechanicalObject::WriteVecCoord writeX = dofs->writePositions();
+        for (sofa::Index id = 0; id < nbrDofs; id++)
+        {
+            for (unsigned int i = 0; i < writeX[0].size(); i++)
```
Comment (alxbilger) [inline modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp]: I assume it leads to the same result if you take `writeX[0].size()` or `writeX[id].size()`?

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp [hunk 3]
```diff
@@ -156,6 +158,91 @@ struct FixedConstraint_test : public BaseTest
...
+            {
+                writeX[id][i] = 1.0 * id + 0.1 * i;
```
Comment (alxbilger) [inline modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp]: You can drop the `1.0 *`

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp [hunk 4]
```diff
@@ -156,6 +158,91 @@ struct FixedConstraint_test : public BaseTest
...
+        typename FixedConstraint::SPtr cst = sofa::core::objectmodel::New<FixedConstraint>();
+        helper::vector<Index> indices = { 0, 1, 2 };
+        cst->d_indices.setValue(indices);
+        node->addObject(cst);
+
+
+        /// Init simulation
+        sofa::simulation::getSimulation()->init(root.get());
+
+        /// Perform one time step
```
Comment (alxbilger) [inline modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp]: you perform 2 time steps

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp [hunk 5]
```diff
@@ -156,6 +158,93 @@ struct FixedConstraint_test : public BaseTest
...
+
+        /// Add Mass
+        createUniformMass<DataTypes>(node, *dofs.get());
+
+        /// Add force
+        typename ForceField::SPtr forceField = addNew<ForceField>(node);
+        
+        // create a force vector
+        Deriv force;
+        auto typeSize = force.size();
```
Comment (hugtalbot) [inline modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp:194]: here the size could be checked by comparing to the nbrDofs, right ?

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp [hunk 6]
```diff
@@ -156,6 +158,93 @@ struct FixedConstraint_test : public BaseTest
...
+        /// Fill position and force
+        typename MechanicalObject::WriteVecCoord writeX = dofs->writePositions();
+        for (sofa::Index id = 0; id < nbrDofs; id++)
+        {
+            for (unsigned int i = 0; i < typeSize; i++)
+            {
+                writeX[id][i] = id + 0.1 * i;
+            }
+
+            forceField->setForce(id, force);
```
Comment (hugtalbot) [inline modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp:208]: forceField is a "ForceField", an abstract class. Will this work? when I look at the addForce function for instance, it is virtual pure in ForceField class.

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp [hunk 7]
```diff
@@ -156,6 +158,93 @@ struct FixedConstraint_test : public BaseTest
...
+        for (unsigned i = 0; i < typeSize; i++)
+            force[i] = 10;
+
+        /// Fill position and force
+        typename MechanicalObject::WriteVecCoord writeX = dofs->writePositions();
+        for (sofa::Index id = 0; id < nbrDofs; id++)
+        {
+            for (unsigned int i = 0; i < typeSize; i++)
+            {
+                writeX[id][i] = id + 0.1 * i;
```
Comment (hugtalbot) [inline modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp]: you are here defining the initial values of your DOF (positions) right ?
Would it be :
- point0 [0. 0. 0.]
- point1 [1.0 1.1 1.2]
- point2 [2.0 2.2 2.4]
- ...

is it correct?

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp [hunk 8]
```diff
@@ -156,6 +158,93 @@ struct FixedConstraint_test : public BaseTest
...
+
+        typename MechanicalObject::ReadVecCoord readX = dofs->readPositions();
+
+        /// check info before topological changes
+        EXPECT_EQ(tCon->getPoints().size(), nbrDofs);
+        EXPECT_EQ(readX[0][0], 0);
+        EXPECT_EQ(readX[1][0], 1);
+        EXPECT_EQ(readX[2][0], 2);
+        EXPECT_NEAR(readX[3][0], 4.32231, 1e-4);
+        EXPECT_NEAR(readX[4][0], 5.32231, 1e-4);
```
Comment (hugtalbot) [inline modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp:233]: I guess this is what you measured experimentally, or are these analytical values?

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp [hunk 9]
```diff
@@ -156,6 +158,93 @@ struct FixedConstraint_test : public BaseTest
...
+
+        /// remove some points from topological mechanism
+        sofa::helper::vector< sofa::Index > indicesRemove = {0, 2, 3};
+        tMod->removePoints(indicesRemove, true);
+        nbrDofs -= sofa::Size(indicesRemove.size());
+
+        /// new positions are now: {id[4], id[1]}  because remove use swap + pop_back
+        EXPECT_EQ(tCon->getPoints().size(), nbrDofs);
+        EXPECT_NEAR(readX[0][0], 5.32231, 1e-4);
+        EXPECT_EQ(readX[1][0], 1);
```
Comment (hugtalbot) [inline modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp]: use 1.0 instead of 1 no? (avoid confusion)

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp (hunk 7 above)
Comment (hugtalbot) [reply modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp]: if so, these values could be written as comment to make it explicit

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp (hunk 5 above)
Comment (epernod) [reply modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp:194]: no it is size of Deriv, Vec1,2 3  etc.

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp (hunk 6 above)
Comment (epernod) [reply modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp:208]: no forcefield is: ```typedef component::forcefield::ConstantForceField<DataTypes> ForceField;```
This was already there, we can change the name for more clarity

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp (hunk 7 above)
Comment (epernod) [reply modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp]: 0; 0.1; 0.2
1; 1.1; 1.2
2; 2.1; 2.2

like a grid

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp (hunk 8 above)
Comment (epernod) [reply modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp:233]: measured

Comment (epernod) [reply modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp:233]: but you should be able, there is timestep, and constant force without gravity over 2 timestep.

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp (hunk 9 above)
Comment (epernod) [reply modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp]: same same for EQ I assume it cast to float

Comment (epernod) [reply modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp]:
```suggestion
        EXPECT_NEAR(readX[1][0], 1.0, 1e-4);
```

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp [hunk 10]
```diff
@@ -156,6 +158,93 @@ struct FixedConstraint_test : public BaseTest
...
+        sofa::simulation::getSimulation()->animate(root.get(), 0.1);
+
+        typename MechanicalObject::ReadVecCoord readX = dofs->readPositions();
+
+        /// check info before topological changes
+        EXPECT_EQ(tCon->getPoints().size(), nbrDofs);
+        EXPECT_EQ(readX[0][0], 0);
+        EXPECT_EQ(readX[1][0], 1);
+        EXPECT_EQ(readX[2][0], 2);
+        EXPECT_NEAR(readX[3][0], 4.32231, 1e-4);
```
Comment (epernod) [inline modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp]:
```suggestion
        EXPECT_NEAR(readX[3][0], 4.32231, 1e-4); // compare to computed values
```

File: modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp (hunk 7 above)
Comment (epernod) [reply modules/SofaBoundaryCondition/SofaBoundaryCondition_test/FixedConstraint_test.cpp]:
```suggestion
                writeX[id][i] = id + 0.1 * i;  // create position filled as a grid:  0; 0.1; 0.2 ...  \n  1; 1.1; 1.2 ... \n 2; 2.1; 2.2 ...
```
