### PR TITLE
[SofaKernel] FIX Mat::transpose() and Mat::invert()

### LINKED ISSUE #280: No Mat::inverted() function in defaulttype::Mat
After spending half a day struggling on a little piece of code, I finally found out that my call to invertMatrix didn't return the correct result:

In Sofa, calling 
```
Matrix3 M;
M.invert(M);

``` 
returns a grotesque bullshit, because "from" and "dest" are the same, and no copy is made, so values are changed and read at the same time.
I understand that in terms of performance, avoiding a useless copy is good, but there is no warning message of any kind, not even as a comment over the function.

For the `transpose()` function, there is an additional` transposed()` method that directly stores the transposed matrix in its initial data structure.
I suggest that an `inverted() `method be added to `Mat`, and a little comment above the `invertMatrix()` function be added to warn about this specific problem.

What do you think?
If it sounds good to you, I can take care of it. If you see a better way of warning the user about this behavior, or consider that removing entirely the issue by making a temporary copy of the value is not aberrant, that would be even better I guess

@hugtalbot @guparan 

______________________________________________________

Suggested labels:

### PR DESCRIPTION
**Pull request by marques-bruno**
when passing "this" as argument, forcing object copy to avoid unexpected results
Fixes #280 

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by marques-bruno** [comment]
Not a big fan of the reinterpret_cast in the transpose() method, but it's the only way to check wether or not a copy is needed...

**Comment by damienmarchal** [comment]
[ci-build]

File: SofaKernel/framework/sofa/defaulttype/Mat.h [hunk 1]
```diff
@@ -327,10 +327,15 @@ class Mat : public helper::fixed_array<VecNoInit<C,real>,L>
     /// Set matrix as the transpose of m.
     void transpose(const Mat<C,L,real> &m)
     {
-        for (int i=0; i<L; i++)
-            for (int j=0; j<C; j++)
-                this->elems[i][j]=m[j][i];
-    }
+				if (L == C && reinterpret_cast<Mat<C,L,real>*>(this) == &m)
```
Comment (maxime-tournier) [inline SofaKernel/framework/sofa/defaulttype/Mat.h]: Somewhat cleaner:
```c++
template<int I>
static bool self_transpose(const Mat<I, I, real>& lhs, const Mat<I, I, real>& rhs) {
    return &lhs == &rhs;
}

template<int I, int J>
static bool self_transpose(const Mat<I, J, real>& lhs, const Mat<J, I, real>& rhs) {
    return false;
}
```
Then test using:
```c++
if(self_transpose(*this, m) ) { ... } else { ... }
```

File: SofaKernel/framework/sofa/defaulttype/Mat.h [hunk 2]
```diff
@@ -599,10 +604,26 @@ class Mat : public helper::fixed_array<VecNoInit<C,real>,L>
...
+			Mat<L,C,real> m = *this;
+			invertMatrix(*this, m);
+			return *this;
+		}
+
     /// Invert matrix m
     bool invert(const Mat<L,C,real>& m)
     {
-        return invertMatrix(*this, m);
+				if (&m == this)
```
Comment (maxime-tournier) [inline SofaKernel/framework/sofa/defaulttype/Mat.h]: You probably need to `assert( L == C && "cannot invert a non-square matrix");` at some point.

Or even better, only define `invert` when the matrix is square.

File: SofaKernel/framework/sofa/defaulttype/Mat.h [hunk 3]
```diff
@@ -327,10 +327,15 @@ class Mat : public helper::fixed_array<VecNoInit<C,real>,L>
...
     {
-        for (int i=0; i<L; i++)
-            for (int j=0; j<C; j++)
-                this->elems[i][j]=m[j][i];
-    }
+				if (L == C && reinterpret_cast<Mat<C,L,real>*>(this) == &m)
+						this->operator =(transposed());
+				else
+				{
+						for (int i=0; i<L; i++)
```
Comment (maxime-tournier) [inline SofaKernel/framework/sofa/defaulttype/Mat.h]: also, spaces instead of tabs please

**Comment by marques-bruno** [comment]
@maxime-tournier I believe the last commits takes your input into consideration (if I didn't miss anything)
Looking forward your feedback

**Comment by guparan** [comment]
Any idea why building acd79fe caused more than 20 new unit test failures?

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by marques-bruno** [comment]
PR ready?

**Comment by guparan** [comment]
The 20 new unit tests failures are still there, certainly caused by 092b19fd8e922d155a459de09f002f1815ce9a16.

**Comment by marques-bruno** [comment]
I take a look

File: SofaKernel/framework/sofa/defaulttype/Mat.h [hunk 4]
```diff
@@ -342,10 +360,10 @@ class Mat : public helper::fixed_array<VecNoInit<C,real>,L>
         return m;
     }
 
-    /// Transpose current matrix.
+    /// Transpose the square matrix.
     void transpose()
     {
-        static_assert(L == C, "");
+        assert(L == C && "Cannot self-transpose a non-square matrix. Use transposed() instead");
```
Comment (matthieu-nesme) [inline SofaKernel/framework/sofa/defaulttype/Mat.h]: the static_assert was better here (adding the comment)

Comment (maxime-tournier) [reply SofaKernel/framework/sofa/defaulttype/Mat.h]: If i'm not mistaken the `static_assert` will be triggered for any non-square matrix regardless of transpose being called or not.

It *is* possible to make this check statically but it requires more boilerplate.

**Comment by marques-bruno** [comment]
Hum... I messed up somehow in my previous commit. Did a pull -r and everyting went to hell for some reason...
I have 689 files with changes in the PR, which is quite aweful for a small modification in 2 files...
How could I fix this? :/
My apologies

**Comment by marques-bruno** [comment]
Hi dear reviewers,
I'm waiting for the ci-build, but I believe that the problems are now solved, and the fix now comes with a few unit tests =)
@matthieu-nesme I also restored the static_assert that I previously removed so the code is not only better.
Any other suggestion?

File: SofaKernel/framework/sofa/defaulttype/Mat.h [hunk 5]
```diff
@@ -324,12 +324,30 @@ class Mat : public helper::fixed_array<VecNoInit<C,real>,L>
...
+    }
+
     /// Set matrix as the transpose of m.
     void transpose(const Mat<C,L,real> &m)
     {
-        for (int i=0; i<L; i++)
-            for (int j=0; j<C; j++)
-                this->elems[i][j]=m[j][i];
+        if (canSelfTranspose(*this, m))
+            *this = transposed();
```
Comment (matthieu-nesme) [inline SofaKernel/framework/sofa/defaulttype/Mat.h]: rather than creating a full temporary, and then copying everyone, what you could do is to iterate only on a triangular matrix and to swap with the other triangular. Something like:

```
for (int i=0; i<L; i++)
    for (int j=i+1; j<C; j++)
        std::swap( this->elems[i][j], this->elems[j][i] );
```

**Review by matthieu-nesme — CHANGES_REQUESTED** [review]
just proposing a small improvement.

File: SofaKernel/framework/sofa/defaulttype/Mat.h (hunk 5 above)
Comment (marques-bruno) [reply SofaKernel/framework/sofa/defaulttype/Mat.h]: @matthieu-nesme : copied the behavior of `void transpose()`.
Thanks for your review!

File: SofaKernel/framework/sofa/defaulttype/Mat.h [hunk 6]
```diff
@@ -324,12 +324,40 @@ class Mat : public helper::fixed_array<VecNoInit<C,real>,L>
...
+
     /// Set matrix as the transpose of m.
     void transpose(const Mat<C,L,real> &m)
     {
-        for (int i=0; i<L; i++)
-            for (int j=0; j<C; j++)
-                this->elems[i][j]=m[j][i];
+        if (canSelfTranspose(*this, m))
+        {
+            for (int i=0; i<L; i++)
```
Comment (matthieu-nesme) [inline SofaKernel/framework/sofa/defaulttype/Mat.h:345]: replacing this block with `this->transpose()`?

File: SofaKernel/framework/sofa/defaulttype/Mat.h [hunk 7]
```diff
@@ -342,17 +370,19 @@ class Mat : public helper::fixed_array<VecNoInit<C,real>,L>
...
+    /// Transpose the square matrix.
     void transpose()
     {
-        static_assert(L == C, "");
+        static_assert(L == C, "Cannot self-transpose a non-square matrix. Use transposed() instead");
         for (int i=0; i<L; i++)
+        {
             for (int j=i+1; j<C; j++)
             {
                 real t = this->elems[i][j];
```
Comment (matthieu-nesme) [inline SofaKernel/framework/sofa/defaulttype/Mat.h]: `std::swap( this->elems[i][j], this->elems[j][i] );`

**Review by matthieu-nesme — CHANGES_REQUESTED** [review]
I am looking for the "petite bête" but while modifying Mat.h, It's worth polishing it.
Thanks.

File: SofaKernel/framework/sofa/defaulttype/Mat.h (hunk 7 above)
Comment (marques-bruno) [reply SofaKernel/framework/sofa/defaulttype/Mat.h]: Thanks @matthieu-nesme,

What are the benefits of using std::swap, except for code clarity?
I don't know the difference in complexity between std::swap and a manual swap of the variables.
If I look into the stl doc, it seems that, in terms of complexity, std::swap is the same implementation as mine, with the difference that instead of a call to the simple assignement operator, it also calls std::move as it could optimize the assignements in specific cases (specific datatypes, but not in the case of doubles or float values to my understanding)
So it seems to me that in terms of performances my implementation is quite the same.
Though, if I would declare 't' outside of the nested loop, I would save L*(C-1) construction of this variable (modulo compiler optimizations), which I couldn't do with a call to std::swap. (untested assumption... )

So should I correct the code to:
```
real t;
for (int i=0; i<L; i++)
   for (int j=i+1; j<C; j++)
   {
     t = this->elems[i][j];
     this->elems[i][j] = this->elems[j][i];
     this->elems[j][i] = t;
   }

```
or

```
for (int i=0; i<L; i++)
   for (int j=i+1; j<C; j++)
   {
     std::swap(this->elems[i][j], this->elems[j][i]);
   }

```

Comment (matthieu-nesme) [reply SofaKernel/framework/sofa/defaulttype/Mat.h]: To me std::swap is better for clarity and I trust the STL to provide the best possible implementation regarding the platform so you do not have to worry about it.
if you declare t as const inside the loop, the compiler optimization will allocate it only once and share it anyway (I guess it should also work if it is not const, but you are not helping the compiler!)

Comment (marques-bruno) [reply SofaKernel/framework/sofa/defaulttype/Mat.h]: Ok,
Thanks for your input, I rectify accordingly =)

**Comment by guparan** [comment]
Hi @lagarkane, is this finally ready? :-)

**Comment by marques-bruno** [comment]
I believe it is now! @matthieu-nesme , everything ok?

File: SofaKernel/framework/sofa/defaulttype/Mat.h (hunk 6 above)
Comment (marques-bruno) [reply SofaKernel/framework/sofa/defaulttype/Mat.h:345]: Do you mean replacing the nested for-loop in 
`if (canSelfTranspose(*this, m))`
by a call to` this->transpose()`?
This would cause the static-assert to trigger, hence the suggestion from  @maxime-tournier to use templated canSelfTranspose() functions.

Comment (matthieu-nesme) [reply SofaKernel/framework/sofa/defaulttype/Mat.h:345]: ok. good to me!

**Review by matthieu-nesme — APPROVED** [review]

**Comment by damienmarchal** [comment]
[ci-build] (to sync with the latest merge of GIL.
