### PR TITLE
[SofaBaseMechanics] Fix warning scene mass

### LINKED ISSUE #724: [UniformMass] Warnings popping up when they shouldn't
> 
> [WARNING] [UniformMass(UniformMass)] totalMass value overriding the value of the attribute vertexMass. 
> vertexMass = totalMass / nb_dofs. 
> To remove this warning you need to set either totalMass or vertexMass data field, but not both.

This warning should show up when both vertexMass and totalMass are set. Though setting totalMass alone still triggers the warning
______________________________________________________

Suggested labels:

### PR DESCRIPTION
**Pull request by hugtalbot**
FIX some scene files using the mass and having issues with mass datanames (_totalmass_ instead of _totalMass_)
FIX initialization in UniformMass.cpp due to wrong default filename in Rigid case

Fix #724

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

File: SofaKernel/modules/SofaBaseMechanics/UniformMass.cpp [hunk 1]
```diff
@@ -430,8 +431,8 @@ template<> SOFA_BASE_MECHANICS_API
 void UniformMass<Rigid3dTypes, Rigid3dMass>::constructor_message()
 {
     d_filenameMass.setDisplayed(true) ;
-    d_filenameMass.setReadOnly(false) ;
-    d_filenameMass.setValue("") ;
+    d_filenameMass.setReadOnly(true) ;
+    d_filenameMass.setValue("unused") ;
```
Comment (epernod) [inline SofaKernel/modules/SofaBaseMechanics/UniformMass.cpp:435]: what does the "unused" value do ?

File: examples/Components/collision/RuleBasedContactManager.scn [hunk 2]
```diff
@@ -65,7 +65,7 @@
 		<EulerImplicit />
 		<CGLinearSolver iterations="25" tolerance="1e-5" threshold="1e-5"/>
         <MechanicalObject template="Rigid" scale="5.0" dx="-38" dy="0" />
-        <UniformMass filename="BehaviorModels/torus.rigid" totalMass="5000.0" />
+        <UniformMass filename="BehaviorModels/torus.rigid"/>
```
Comment (epernod) [inline examples/Components/collision/RuleBasedContactManager.scn:68]: for me uniformMass  was applying a value: totalMass/nbrVertex for each point. What data is this file giving?

Comment (hugtalbot) [reply examples/Components/collision/RuleBasedContactManager.scn:68]: this is a file giving info for rigid that specifies the mass per vertex (vertexMass)

UniformMass can take two data for its initialization : either totalMass or vertexMass

File: SofaKernel/modules/SofaBaseMechanics/UniformMass.cpp (hunk 1 above)
Comment (hugtalbot) [reply SofaKernel/modules/SofaBaseMechanics/UniformMass.cpp:435]: It set a default value to the filename data.
 this is maybe not really clean for the filename initialization process. I agree

File: examples/Components/collision/RuleBasedContactManager.scn (hunk 2 above)
Comment (epernod) [reply examples/Components/collision/RuleBasedContactManager.scn:68]: ok thanks!

**Comment by epernod** [comment]
@hugtalbot do you confirm it will solve the issue #779 ?

**Comment by epernod** [comment]
yes it is what I wanted to point... cool!

**Review by epernod — APPROVED** [review]
