### PR TITLE
[GUI] Improve advanced timer

### LINKED ISSUE #357: Advanced timer usage at initialization
While there are some pretty nice ideas going on considering the improvement the output of the advanced timer #348, to my knowledge (please correct me if I am wrong!), the component has some shortcomings:
1. The timing output does not show up when using the batch gui, i.e. when specifying -g batch over the command line. Together with @ggrosshenny, we already took care of this in the work related to #348, a pull request will follow soon.
2. The advanced timer can not be used at the initialization, i.e. in methods like init and I believe as well the backward init

To resolve the second point, I propose to change the variable computationTimeSampling to an integer (see Main.cpp, line 182). When set at 
- a negative integer c, it does output the timings of the initialization, but at every time step -c
- 0, it only outputs the timings of the initialization
- a positive integer c, it does not output the timings of the initialization and at every time step c

Thus the persons having used the timer before will not have any impact on their potential scripts using the SOFA output.
An implementation already has been started with @ggrosshenny, but it is not clear where an insertion has the less impact and yields the results. @ggrosshenny, could you precise that please?

Has there been any work considering this point?
Do you have any propositions how to address it?

Label propositions: discussion, bug

### PR DESCRIPTION
**Pull request by chrijopa**
This pull request allows the usage of the advanced timer 
1. In the standard way
`runSofa -c 1`
2. Only for the init functions:
`runSofa -c 0`
3. For the init function and for every second step:
`runSofa -c -2`

Moreover, the usage of the advanced timer in batch mode works again:
`runSofa -c -2 -g batch -n 10`

Fixes #357 
______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

File: applications/projects/runSofa/Main.cpp [hunk 1]
```diff
@@ -185,7 +185,7 @@ int main(int argc, char** argv)
     bool        noAutoloadPlugins = false;
     int         nbIterations = BatchGUI::DEFAULT_NUMBER_OF_ITERATIONS;
     unsigned int nbMSSASamples = 1;
-    unsigned    computationTimeSampling=0; ///< Frequency of display of the computation time statistics, in number of animation steps. 0 means never.
+    int    computationTimeSampling=0; ///< Frequency of display of the computation time statistics, in number of animation steps. 0 means never.
```
Comment (untereiner) [inline applications/projects/runSofa/Main.cpp]: where is the computationTimeSampling variable negative ?
I can't find it

**Comment by damienmarchal** [comment]
Hello,

Thank for the PR. The added feature is nice and should be merged but the way it hack the command line by allowing "-2" is very confusing. 

Why not doing: 
The standard way
```runSofa -c 1```

Only for the init functions:
```runSofa -b```
(as -i is already taken maybe -b to begin is a good choice)

For the init function and for every second step:
```runSofa -c 2 -b```

It would clearly separate the concerns instead of encoding different behavior in the same variable.

**Comment by chrijopa** [comment]
Thank you Damien for the important remark considering "-2", I was not aware of this problem. I will look into further details tomorrow.

File: applications/projects/runSofa/Main.cpp [hunk 2]
```diff
@@ -418,7 +420,21 @@ int main(int argc, char** argv)
         loadVerificationData(verif, fileName, groot.get());
     }
 
+    if( computationTimeSampling<1 )
+    {
+        sofa::helper::AdvancedTimer::setEnabled("Init", true);
+        sofa::helper::AdvancedTimer::setInterval("Init", 1);
+        sofa::helper::AdvancedTimer::setOutputType("Init", computationTimeOutputType);
+        sofa::helper::AdvancedTimer::begin("Init");
```
Comment (jnbrunet) [inline applications/projects/runSofa/Main.cpp:399]: There is a duplicated begin("Init") here

**Comment by guparan** [comment]
[ci-build]

File: applications/sofa/gui/BatchGUI.cpp [hunk 3]
```diff
@@ -51,18 +51,23 @@ int BatchGUI::mainLoop()
 {
     if (groot)
     {
-
+        std::cout << "Computing "<<nbIter<<" iterations." << std::endl;
+        sofa::helper::AdvancedTimer::begin("Animate");
+        sofa::helper::AdvancedTimer::end("Animate");
+        sofa::helper::AdvancedTimer::begin("Animate");
```
Comment (guparan) [inline applications/sofa/gui/BatchGUI.cpp]: @chrijopa: Why begin then end immediately?

File: applications/sofa/gui/BatchGUI.cpp [hunk 4]
```diff
@@ -51,18 +51,23 @@ int BatchGUI::mainLoop()
...
         sofa::simulation::getSimulation()->animate(groot.get());
+        std::cout << sofa::helper::AdvancedTimer::end("Animate", groot.get()) << std::endl;
```
Comment (guparan) [inline applications/sofa/gui/BatchGUI.cpp]: Please use `msg_info` instead of `std::cout`

File: applications/projects/runSofa/Main.cpp [hunk 5]
```diff
@@ -418,7 +422,21 @@ int main(int argc, char** argv)
...
+        sofa::helper::AdvancedTimer::end("Init");
+        sofa::helper::AdvancedTimer::begin("Init");
+    }
+
     sofa::simulation::getSimulation()->init(groot.get());
+    if( computationTimeAtBegin )
+    {
+        std::cout << sofa::helper::AdvancedTimer::end("Init", groot.get()) << std::endl;
```
Comment (guparan) [inline applications/projects/runSofa/Main.cpp]: Please use `msg_info` instead of `std::cout`

**Review by guparan — CHANGES_REQUESTED** [review]

File: applications/projects/runSofa/Main.cpp (hunk 2 above)
Comment (chrijopa) [reply applications/projects/runSofa/Main.cpp:399]: There was a bug in the advanced timer (variable initialization at -1 instead of 0), that I just removed. Should be fine but it is good if that is double checked.

**Comment by guparan** [comment]
[ci-build]

**Comment by guparan** [comment]
[ci-build]

**Review by guparan — APPROVED** [review]

**Comment by ErwanDouaille** [comment]
@hugtalbot I didn't test it but the argument parser stuff looks good to me. I would suggest to not define b/o characters because, AFAIK, advance timer is not often used so maybe there is better use of b/o character.
