### PR TITLE
[Multithreading, THMPGSpatialHashing] Fix build with Boost 1.64.0

### LINKED ISSUE #316: Multithreading cannot build with Boost 1.64
With Boost 1.64, at least on Mac, Multithreading build fails with the following message:
```FAILED: applications/plugins/MultiThreading/CMakeFiles/MultiThreading.dir/src/TaskSchedulerBoost.cpp.o 
/usr/local/bin/ccache  clang++ -Qunused-arguments -Wno-deprecated-declarations  -DMultiThreading_EXPORTS -Iinclude -I../applications/plugins/MultiThreading/.. -isystem /usr/local/include -I../SofaKernel/SofaBase/../modules -I../SofaKernel/SofaSimulation/../modules -I../SofaKernel/framework/sofa/core/../.. -I../SofaKernel/framework/sofa/helper/../.. -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks -I../SofaKernel/extlibs/eigen-3.2.7 -ISofaKernel/SofaFramework -I../SofaKernel/extlibs/tinyxml -I../SofaKernel/framework/sofa/defaulttype/../.. -I../SofaMisc/../modules -I../SofaKernel/SofaCommon/../modules -isystem=/opt/local/include/Qt -Wall -W -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.11 -fPIC   -DSOFA_MULTITHREADING_PLUGIN -std=gnu++11 -MD -MT applications/plugins/MultiThreading/CMakeFiles/MultiThreading.dir/src/TaskSchedulerBoost.cpp.o -MF applications/plugins/MultiThreading/CMakeFiles/MultiThreading.dir/src/TaskSchedulerBoost.cpp.o.d -o applications/plugins/MultiThreading/CMakeFiles/MultiThreading.dir/src/TaskSchedulerBoost.cpp.o -c ../applications/plugins/MultiThreading/src/TaskSchedulerBoost.cpp
../applications/plugins/MultiThreading/src/TaskSchedulerBoost.cpp:192:18: error: overload resolution selected deleted operator '='
                        mTaskMutex.v_ = 0L;
                        ~~~~~~~~~~~~~ ^ ~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/atomic:1654:18: note: candidate function has been explicitly deleted
    atomic_flag& operator=(const atomic_flag&) = delete;
                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/atomic:1655:18: note: candidate function has been explicitly deleted
    atomic_flag& operator=(const atomic_flag&) volatile = delete;
                 ^
1 error generated.
```

This plugin should either be updated with the new boost API, or get rid of boost dependency.
I don't know this plugin enough...

______________________________________________________

Suggested labels:

### PR DESCRIPTION
**Pull request by guparan**
This PR kind of fixes #316 
Concerning Multithreading plugin, it still would be better to get rid of Boost dependency as stated by @fjourdes in #316.

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

File: applications/plugins/MultiThreading/src/TaskSchedulerBoost.cpp [hunk 1]
```diff
@@ -189,7 +189,6 @@ namespace sofa
 			mTaskCount		= 0;
 			mFinished		= false;
 			mCurrentStatus = NULL;
-			mTaskMutex.v_ = 0L;
```
Comment (damienmarchal) [inline applications/plugins/MultiThreading/src/TaskSchedulerBoost.cpp:192]: Ok ... so while digging to fix the failing scenes it seems that this changes generated two new failures. 
This is because not setting v_ to zero leave the spinlock uninitialized and thus in a "locked" state. 
So no-one can grab it. 

I'm not sure how to fix that now as I have an old version of boost.
